name: 'Full Flow'

env:
  VERSION: 3.2.0
  BUILD_TYPE: Release
  ARCH: x64
  VCPKG_DEFAULT_VCPKG_TRIPLET: x64-windows
  VCPKG_TRIPLET: x64-windows
  VCPKG_CONFIG: Release

on:
  push:
    branches:
      - master
      - oss-release

  pull_request:
    branches:
      - master

  workflow_dispatch:

jobs:
  # builds native codecs binary for all supported OSes
  build-native:
    runs-on: windows-latest 
    name: 'build'

    steps:
      
    - uses: actions/checkout@v3
      with:
        submodules: true

    - uses: friendlyanon/setup-vcpkg@v1
      # seems like the absense of commit hash expects vcpkg submodule, i don't want that
      with:
        committish: 1ba9a2591f15af5900f2ce2b3e2bf31771e3ac48 
        # set to false to clear any cache in case of build errors
        cache: false

    - name: configure
      run: cmake -B build -S . -D CMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -D "CMAKE_TOOLCHAIN_FILE=${{ env.VCPKG_ROOT }}/scripts/buildsystems/vcpkg.cmake" -D "VCPKG_TARGET_TRIPLET=${{ env.VCPKG_TRIPLET }}"
      working-directory: . 

    - name: build
      run: cmake --build build --config ${{ env.VCPKG_CONFIG }}
      working-directory: . 

    - name: pack
      run: cpack -C ${{ env.BUILD_TYPE }}
      working-directory: build

    - name: debug
      run: ls -R
      working-directory: . 

